### PR TITLE
Gin and tonic flat

### PR DESCRIPTION
**Pull request by Plokhi**

### CODE REVIEW

**Comment by fredli74** [comment]
Force pushed some changes because our main branches have diverged. Try pulling or resetting your Plokhi/main to my fredli74/main

**Comment by Plokhi** [comment]
how do i do that?

**Comment by fredli74** [comment]
When you made changes to your main branch last time, I made things worse because I did not merge your changes, I just picked them and applied them to my main. This means we have the same changes, but with different commits, so git cannot figure out the history anymore. The easiest solution now is resetting.

First make sure you're in your main branch because I have not merged all your pull requests yet, so you do not want to overwrite them.

`git checkout main`

Then tell your repository to just throw everything away and use what was in the origin last time you pulled.

`git reset --hard origin/main`

Now there is no conflict anymore, so you can bring it up to date with mine.

`git pull`

After that, your main is in sync with mine, so next time you create a branch the origin will be correct and GitHub will have no problem merging them when doing a pull request.

For the branches and pull requests you have active, don't worry, I'll solve that, but I need some time for some other changes before I do that.

**Comment by fredli74** [comment]
I just realized that my instructions are probably wrong. For you, I think the origin is your fork, not my repository. You will most likely have to add a reference to my repository first and call it something, like "upstream" for example.

`git remote add upstream https://github.com/fredli74/microtonic-skins.git`

Fetch it 
`git fetch upstream`

Make sure you're in main
`git checkout main`

Reset it
`git reset --hard upstream/main`

Overwrite your fork
`git push origin main --force`

**Comment by Plokhi** [comment]
says " fatal: not a git repository (or any of the parent directories):
.git"
for the first command

**Comment by fredli74** [comment]
Ah, you must do it inside your working folder, or make a new clone.
```
git clone https://github.com/Plokhi/microtonic-skins.git
cd microtonic-skins
```

**Pull request merged**
