### PR TITLE
Polishing pixels

### PR DESCRIPTION
**Pull request by l4rs3rik**
Removed the ugly tonicB and tonicR and added version 2.0 of tonica. Less is more.

### CODE REVIEW

**Comment by l4rs3rik** [comment]
Resolved conflict by doing a revert to the previous tonicR changes.

**Comment by fredli74** [comment]
The revert in f6862a0 puts back files that you removed in 984d9de, is tonicB and tonicR supposed to be removed completely?

**Comment by fredli74** [comment]
The conflict was my bad, I did a squash and merge (which I did not have to do since you only had one commit).

The best way to resolve it is to pull your main so it is in sync with my main, then do an interactive rebase of the PolishingPixels branch on top of the main branch, where you drop the last revert commit. It should then figure out that your f71671f and my 72ac188 are the same changes and work the rest out.

**Comment by l4rs3rik** [comment]
Yes the tonicB and tonicR removal is a conscious decision. 

So do you want me to start over, like we throw this pull request away and I create a new one from a new fresh branch?

**Comment by fredli74** [comment]
Actually, I do not think you need to restart the pull request. If you make updates to your branch and push them, the pull request will be updated, even if you force push (as far as I know).

You need to make an interactive rebase. What git client are you using? With the command line it would typically go like this.
```
git switch main
git pull
git switch PolishingPixels
git rebase --interactive main
   << drop f6862a0 and also f71671 if it shows up >>
git push --force
```

**Comment by fredli74** [comment]
Oh, apparently I could do it  :)

**Pull request merged**
