### PR TITLE
bugfixes and minor adjustments

### PR DESCRIPTION
**Pull request by l4rs3rik**

### CODE REVIEW

**Comment by fredli74** [comment]
We got rid of the cog icon for the script button (because it was mistakenly identified as a preference button). I did a Q&D fix of it on your skins previously (ad472f5c5f062c0a6b8fa3d4de2316c02ddfdb00 d1318f5577ca2f6c7dc261fcfdc7b2af7942dec4), but now the cog is back on your latest thumbnail.

If you have time to fix the sources you use, I think that would be better than me monkey patching the pixels in the corner again. 😊

**Comment by fredli74** [comment]
Plain version can be found in the "factory" layer in `/Template/buttonicons_x2.psd`

**Comment by l4rs3rik** [comment]
> We got rid of the cog icon for the script button (because it was mistakenly identified as a preference button). I did a Q&D fix of it on your skins previously ([ad472f5](https://github.com/fredli74/microtonic-skins/commit/ad472f5c5f062c0a6b8fa3d4de2316c02ddfdb00) [d1318f5](https://github.com/fredli74/microtonic-skins/commit/d1318f5577ca2f6c7dc261fcfdc7b2af7942dec4)), but now the cog is back on your latest thumbnail.
> 
> If you have time to fix the sources you use, I think that would be better than me monkey patching the pixels in the corner again. 😊

Sure thing, next commit in my KentuckyBug branch will have updated script button.

**Comment by l4rs3rik** [comment]
A commit with the proper buttonicons is now in place.

**Pull request merged**
